### ISSUE TITLE
Any plans to add this to the Microsoft Store?

### ISSUE THREAD

**Issue by dsent** [bam/edge-contextMenuSearch#1]
https://answers.microsoft.com/en-us/windows/forum/windows_10/right-click-context-menus-in-edge-build-10166/8cc3d898-d84c-4260-87b7-1978a287abd1

Any news on this one? :-)

**Comment by bam** [comment]
Hi!
No, while I don't have a MS Developer's license I can't upload anything to the store. I've tried to make signed package with local cert but something went wrong and I got stuck need to have a license again. And I put it aside...
But I don't know have they opened an opportunity to upload to anybody? I remember there isn't one. There was only way to send request for adding your extension by email or web form. They must accept it... something like this, not so clear to me...
Anyway I think there are a few features to implement and release before publishing. Like url parsing, icons and internationalization... I hope it will be done before xmas. (Though I spend pretty much at work now)

**Comment by NeatNit** [comment]
Beep.

Curious about whether this is coming. It's ever-so-slightly annoying to have to click "Turn on anyway", and besides, putting this on the store will make a lot more people see it.

**Comment by NeatNit** [comment]
@bam yet again I'm nagging you about this because Edge - through no fault of your own - is driving me insane with this. Any chance to put it on the store?

**Comment by bam** [comment]
@NeatNit actually I took pause for fifa's WC and now I'm at vacation. I will come back only at 28 of July. I already fixed your #22 (if I remember right). 
Yep, there're chances I'll put it to the store. (=

**Comment by NeatNit** [comment]
Huzzah!

**Comment by bam** [comment]
@NeatNit @dsent 
I've published my extension to the store. So you can [download](https://www.microsoft.com/store/apps/9NZ9THH1RS1X) and use it without any confirmation on each start of browser from now!
If you will find any bug or will have a feature request, feel free to open an issue here on Github.

P.s. and if it will be not so difficult to you, write a review and rate my extension in Microsoft Store please.
