### ISSUE TITLE
Native supprt for right click search not there in Edge 42.17134.1.0

### ISSUE THREAD

**Issue by notuntoward** [bam/edge-contextMenuSearch#15]
It looks like this app would be useful again, because Edge no longer has support for right click search.  Instead there's an "ask Cortana" right click option, which is probably what nobody wants.

**Comment by bam** [comment]
@notuntoward Yep, I've seen recently and created an [issue](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17423076/) for Edge.
There is no answer yet. And I will look for time to fix current branch.
Just before I've written that note about suspending development I'd found some instability in my extension.
So it needs to be reviewed and fixed…

**Comment by bam** [comment]
@notuntoward 
Well, I have released v1.2.1. So now it can be used, if I haven't missed something on rapid testing.

Anyway v1.2.2 will come on 10th of June already! Watch for updates...
