### ISSUE TITLE
Text beginning with number sign fails to search

### ISSUE THREAD

**Issue by NeatNit** [bam/edge-contextMenuSearch#22]
Try searching for this:

- #FFD700
- #HashTagsAlsoStartWithIt
- What#if#it's#in#the#middle?
- The #1 Edge Extension!

**Comment by bam** [comment]
to check also: https://github.com/bam/edge-contextMenuSearch/projects/1#card-3304552

**Comment by bam** [comment]
Must be replaced with [percent-encoding](https://en.wikipedia.org/wiki/Percent-encoding)
