### ISSUE TITLE
disable option for goto menu

### ISSUE THREAD

**Issue by bam** [bam/edge-contextMenuSearch#23]
Support option to manually disable goto menu and url detection.
Default: enabled.
Reason: more than one context menu items create top level item. So there is one more action(hover) before click. If user doesn't want to have goto and wants to have search item on top level context menu than we need an option to disable all other features of extension and force to have just one top level context menu item.

**Comment by NeatNit** [comment]
I would prefer 3 options for when a URL is detected:
1. Search only
2. Goto only
3. Both (default)

I would use goto only, it's much more likely that I'd want to go to a selected URL than search for it, and I agree that the extra action is a bit annoying.

**Comment by bam** [comment]
That's default chrome's behavior. If URL is detected context menu contains Go to, otherwise Search...
I've already thought that I'd rather create Auto, and two checkboxes for manual setup...
